language: java
jdk: oraclejdk8
services: mongodb
before_install:
- chmod +x gradlew
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  api_key:
    secure: Xjznhv5rLeqxEGywwLUrAXd51r2ZBmloxbvpsKeQdSDCAgayxYCaWaEZVF/vL7jhZRZcJVkRGULQ0DqSJku4InjlNvK87ugddNXd2e07/b2Sd/HIDexGK38WG2vXJwaX/N9U8PEh3tvAbCesaBQH072khVUP9OEwwCLB3a08/HCrTaYodPGvxhS1V5WMiYFqWPDK8Gc4ku0Si+lqePdN/qQnGkTGZcdxaxn0L4NWgebDBHGlDID5aucpKf9ZpI9YcyfrzGKz+N7XYxf2GW61gco0z2BzLLwCICNtT9+O10Nw4EfFMToT1kD5WHsG60cYCT+b0Kh32Fa5AbkBhpp0Cr03V1+S7gyFZnZfwZd8TwgAAFZ+zabKQSH5q0OXZWlkP04dsOEy6mymcgO6RLjUiN5aIfsCC8bOIOBHe/83E3IV0zU+TaAWQ+YcQEQ+UMu9TWpLPGjFkBTaD7ZpiqJsncJleF0uD+cPSbMWQcmi50q4e0x94ai5CYiTcIs4TyOd+ScU0DOvYmUGCvK3DU7M4MQQQN2XOBhpatQ889/nDoINsdFGb7+nb3YshLeg27rsoZdq9xXW9roC9OUhMSmVX021+fFU8kxjRamR7o45dlPFDUJnne4gM2zH2BncC42Xs1rEgbVki94L1Mxyx84LvxtkQLQt+bUiIG71AnPXutY=
  app: incredibleops
  on: master