#Server properties
server:
  port: 8080
  compression:
    enabled: true
    
spring:
  #Mail properties
  mail:
    protocol: imaps
    properties:
      socketFactory: javax.net.ssl.SSLSocketFactory
      fallback: false
      protocol: imaps
      debug: false
      folder: iOps
  #MongoDB propeties
  data:
    mongodb:
      uri: mongodb://localhost/iops
#Logging properties      
logging:
  level:
    org.ht.iops: INFO
    org.ht.iops.aop: INFO
    org.ht.iops.framework.mail.reader.instruction: INFO
    org.ht.iops.events: DEBUG
    org.ht.iops.integration: DEBUG
    org.ht.iops.service: DEBUG
    org.ht.iops.configurations: DEBUG
#Custom properties
custom:
  akamai:
    enabled: true
  integration:
    url: http://localhost:8081
  adapter:
    jira:
      properties:
        name: PISP
  mail:
    protocol: smtp
    port: 587
    auth: true
    debug: false
    socketFactory: javax.net.ssl.SSLSocketFactory
    fallback: true
#End
---
#Cloud configs
spring:
  profiles: cloud
#End
---
#Test configs
spring:
  profiles: test
  #MongoDB propeties
  data:
    mongodb:
      uri: mongodb://localhost/test
#End
---
#Test configs
spring:
  profiles: heroku
#Custom propeties
custom:
  integration:
    url: https://incredibleconnect.herokuapp.com
#End